name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      run: npm install
    - name: Run ESLint
      run: npm run lint
  cypress-tests-desktop:
    needs: eslint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run end-to-end tests on desktop viewport 🧪
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_USER_EMAIL_TEACHER: ${{ secrets.CYPRESS_USER_EMAIL_TEACHER }}
          CYPRESS_USER_PASSWORD_TEACHER: ${{ secrets.CYPRESS_USER_PASSWORD_TEACHER }}
          CYPRESS_USER_EMAIL_STUDENT: ${{ secrets.CYPRESS_USER_EMAIL_STUDENT }}
          CYPRESS_USER_PASSWORD_STUDENT: ${{ secrets.CYPRESS_USER_PASSWORD_STUDENT }}
        with:
          command: npm test